# 定义一些训练组件和中间件的接口数据


PROTOCOL = 'http://'
SERVER_IP = '127.0.0.1'
REMOTE_PORT = 8000

USER_NAME = "zzc997"
USER_PASS = "zzc997997"

LOCAL_PORT = 8997
LOCAL_ROOT_DIR = '/home/zzc/data'
LOCAL_RESULT_DIR = './result'

TASK_COUNTS_MAX = 5
REGISTER_GPU_COUNT = 0